version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
      - MONGO_INITDB_DATABASE=faiss_db
    networks:
      - mongo-network
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  mongo-network:
    driver: bridge
